# Generated by Django 3.2 on 2021-12-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50, verbose_name='Название')),
                ('src', models.ImageField(upload_to='images/', verbose_name='Путь')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('category_name', models.ForeignKey(default='CAT', on_delete=django.db.models.deletion.CASCADE, to='Shop.category')),
                ('imgs', models.ManyToManyField(to='Shop.Img')),
            ],
        ),
    ]
